### ISSUE TITLE
Blocking list operations appear to be broken

### ISSUE THREAD

**Issue by davidh-raybeam** [guilleiguaran/fakeredis#155] opened 2015-10-22 21:43 UTC
Even though `Redis::Connection::Memory` implements `#brpoplpush` and friends, calling any of them throws a `CommandError` with message "unknown command":

```
$ gem install redis fakeredis
[...]
2 gems installed
$ irb -rfakeredis
2.1.2 :001 > r = Redis.new
 => #<Redis client v3.2.1 for redis://127.0.0.1:6379/0> 
2.1.2 :002 > command = :brpoplpush
 => :brpoplpush 
2.1.2 :003 > r.respond_to? command
 => true 
2.1.2 :004 > r.send command, 'a', 'b'
Redis::CommandError: ERR unknown command 'brpoplpush'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/fakeredis-0.5.0/lib/fakeredis/command_executor.rb:12:in `write'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:257:in `block in write'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:236:in `io'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:255:in `write'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:214:in `block (3 levels) in process'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:208:in `each'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:208:in `block (2 levels) in process'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:353:in `ensure_connected'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:195:in `block in call_with_timeout'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:266:in `with_socket_timeout'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis/client.rb:194:in `call_with_timeout'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis.rb:1132:in `block in brpoplpush'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
    from (rvm)/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
    from (rvm)/gems/ruby-2.1.2@fakeredis/gems/redis-3.2.1/lib/redis.rb:1129:in `brpoplpush'
    from (irb):4
    from (rvm)/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

All of the non-blocking list commands work fine.

**Comment by jgagne33** [comment] 2015-11-11 17:04
having this same issue. @davidh-raybeam did you find a solution?

**Comment by davidh-raybeam** [comment] 2015-11-11 19:21
Unfortunately not. Due to approaching deadlines we just switched to running a Redis server in our test environment and flushing it between examples. I'll see if I have a chance to poke at this issue again sometime this weekend.

**Comment by jgagne33** [comment] 2015-11-11 19:34
Ok thanks, we'll do the same and let you know if we come up with anything

**Comment by fatkodima** [comment] 2018-03-26 01:53
Can't reproduce. Looks like this issue is no longer valid?

**Comment by guilleiguaran** [comment] 2018-03-27 23:52
Closing this, feel free to reopen if the issue persists 😊

**Closed by guilleiguaran** 2018-03-27 23:52 UTC
