### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jherdman** [guilleiguaran/fakeredis#200] opened 2017-10-30 18:16 UTC
It seems like there are a few changes in master that would be nice (e.g. `FakeRedis.enabled?` would be awesome). Would it be possible to get a new release?

**Comment by morgoth** [comment] 2017-11-13 11:20
It's a duplicate of https://github.com/guilleiguaran/fakeredis/issues/198
Anyway, new version release would be welcome :-) @guilleiguaran

**Comment by guilleiguaran** [comment] 2018-02-04 18:17
Done: https://rubygems.org/gems/fakeredis/versions/0.7.0

**Closed by guilleiguaran** 2018-02-04 18:17 UTC

**Comment by krzysiek1507** [comment] 2018-03-14 19:16
@guilleiguaran could you please create a tag and release for 0.7.0? :)

**Comment by guilleiguaran** [comment] 2018-03-14 19:17
Sorry, forgot to push the tag.

It's pushed now.

**Comment by krzysiek1507** [comment] 2018-03-14 19:18
Thanks!
